# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kde5-baseapps

# >> macros
# << macros

Summary:    Collection of applications used for file and Internet browsing
Version:    4.97.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-baseapps.yaml
Source101:  kde5-baseapps-rpmlintrc
Requires:   kde5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  kde5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-karchive-devel
BuildRequires:  kf5-kbookmarks-devel
BuildRequires:  kf5-kcoreaddons-devel
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-kconfigwidgets-devel
BuildRequires:  kf5-kdbusaddons-devel
BuildRequires:  kf5-kio-devel
BuildRequires:  kf5-kdelibs4support-devel
BuildRequires:  kf5-kparts-devel
BuildRequires:  kf5-kdesu-devel
BuildRequires:  kf5-kactivities-libs-devel
BuildRequires:  kf5-knewstuff-devel
BuildRequires:  kf5-kfilemetadata-devel
BuildRequires:  kf5-kcmutils-devel
BuildRequires:  kf5-baloo-devel
BuildRequires:  kf5-baloo-widgets-devel
BuildRequires:  phonon-qt5-devel

%description
Collection of applications used for file and Internet browsing


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post

%post
# >> post
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :
# << post

%postun
# >> postun
if [ $1 -eq 0 ] ; then
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null
/usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
fi
# << postun

%files
%defattr(-,root,root,-)
%doc COPYING COPYING.LIB
%{_kde5_bindir}/dolphin
%{_kde5_bindir}/kdialog
%{_kde5_bindir}/kfind
%{_kde5_bindir}/kdepasswd
%{_kde5_bindir}/servicemenuinstallation
%{_kde5_bindir}/servicemenudeinstallation
%{_kde5_plugindir}/*.so
%{_kde5_libdir}/libdolphinprivate.so.*
%{_kde5_libdir}/libkdeinit5_dolphin.so
%{_kde5_datadir}/dolphinpart
%{_datadir}/kservices5/
%{_datadir}/kservicetypes5/
%{_datadir}/templates/
%{_datadir}/applications/
%{_datadir}/config.kcfg/
%{_datadir}/dbus-1/
%{_datadir}/icons/hicolor/
%{_kde5_sysconfdir}/xdg/servicemenu.knsrc
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kde5_includedir}/*.h
%{_kde5_libdir}/libdolphinprivate.so
# >> files devel
# << files devel
